name: 'Grid.ai Run'
inputs:
  run-name:
    required: false
    default: "r$(date '+%y%m%d-%H%M%S')"
    type: string
  script-name:
    required: true
    default: "run.py"
    type: string       
  grid-args:
    required: false
    default: "--localdir --instance_type t2.medium --dependency_file requirements.txt"
    type: string    
  script-args:
    required: false
    default: ""
    type: string   
outputs:
  run-name: 
    value: ${{ steps.run-script.outputs.run-name }}          
  obj-summary: 
    value: ${{ steps.run-status.outputs.obj-summary }}  
  obj-status: 
    value: ${{ steps.run-status.outputs.obj-status }}  
  obj-exit-code: 
    value: ${{ steps.run-status.outputs.obj-exit-code }}          
runs:
  using: "composite"
  steps:
    - id: run-script
      run: |
        export run_name=${{ inputs.run-name }}
        echo "::set-output name=run-name::${run_name}"
        grid run ${{ inputs.grid-args }} --name ${run_name} ${{ inputs.script-name }} ${{ inputs.script-args }} | tee grid.run.log | awk -F: '$1=/grid_name/ {print $2}' test.txt | tr -s '[:blank:]'
      shell: bash 
    - run:
        echo run-name=${{ steps.run-script.outputs.run-name }}
      shell: bash
    - id: run-status
      uses: robert-s-lee/actions@main
      with:
        obj-type: run 
        obj-id: ${{ steps.run-script.outputs.run-name }}
    - run: |
        echo obj-summary ${{ steps.run-status.outputs.obj-summary }}  
        echo obj-status ${{ steps.run-status.outputs.obj-status }}  
        echo obj-exit-code ${{ steps.run-status.outputs.obj-exit-code }}     
      shell: bash
