name: 'Grid.ai Run'
inputs:
  # make sure name is not longer than this
  run_name:
    required: false
    default: "r$(date '+%y%m%d-%H%M%S')"
    type: string
  script_name:
    required: true
    default: "run.py"
    type: string       
  grid_args:
    required: false
    default: "--localdir --instance_type t2.medium --dependency_file requirements.txt"
    type: string    
  script_args:
    required: false
    default: ""
    type: string   
outputs:
  run_name: 
    value: ${{ steps.run_script.outputs.RUN_NAME }}          
runs:
  using: "composite"
  steps:
    - id: run_script
      run: |
        grid run ${{ inputs.grid_args }} --name ${{ inputs.run_name }} ${{ inputs.script_name }} ${{ inputs.script_args }} | tee grid.run.log
        RUN_NAME=$(grep grid_name grid.run.log | cut -d':' -f 2 | sed -e 's/^[[:space:]]*//')
        echo "::set-output name=RUN_NAME::${{ inputs.run_name }}"
      shell: bash
