name: 'Grid.ai Run'
inputs:
  # make sure name is not longer than this
  run_name:
    required: false
    default: "r$(date '+%y%m%d-%H%M%S')"
    type: string
  script_name:
    required: true
    default: "run.py"
    type: string       
  grid_args:
    required: false
    default: "--localdir --instance_type t2.medium --dependency_file requirements.txt"
    type: string    
  script_args:
    required: false
    default: ""
    type: string   
outputs:
  run_name: 
    value: ${{ steps.run_script.outputs.run_name }}          
  obj_summary: 
    value: ${{ steps.run_status.outputs.obj_summary }}  
  obj_status: 
    value: ${{ steps.run_status.outputs.obj_status }}  
  obj_exit_code: 
    value: ${{ steps.run_status.outputs.obj_exit_code }}          
runs:
  using: "composite"
  steps:
    - id: run_script
      run: |
        export run_name=${{ inputs.run_name }}
        echo "::set-output name=run_name::${run_name}"
        grid run ${{ inputs.grid_args }} --name ${run_name} ${{ inputs.script_name }} ${{ inputs.script_args }} | tee grid.run.log
      shell: bash 
    - run:
        echo run_name=${{ steps.run_script.outputs.run_name }}
      shell: bash
    - id: run_status
      uses: robert-s-lee/actions@main
      with:
        obj_type: run 
        obj_id: ${{ steps.run_script.outputs.run_name }}
    - run: |
        echo obj_summary ${{ steps.run_status.outputs.obj_summary }}  
        echo obj_status ${{ steps.run_status.outputs.obj_status }}  
        echo obj_exit_code ${{ steps.run_status.outputs.obj_exit_code }}     
      shell: bash
